tls:
  authorizedEndpoints:
   - endpoint:
       name: metrics
  crypto:
     algorithms: elliptic-curve-386,rsa
nginx:
  server:
    name: example.com
---
spring:
  profiles: development
nginx:
  server:
    name: develop.com
